server:
  port: 8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    config:
      profile: native